// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TinyAppListerExpansion allows custom methods to be added to
// TinyAppLister.
type TinyAppListerExpansion interface{}

// TinyAppNamespaceListerExpansion allows custom methods to be added to
// TinyAppNamespaceLister.
type TinyAppNamespaceListerExpansion interface{}
