apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jupyterlab-with-tinyapp
  name: jupyterlab-with-tinyapp
  namespace: tinyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterlab-with-tinyapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyterlab-with-tinyapp
      name: jupyterlab-with-tinyapp
    spec:
      containers:
        - name: jupyterlab
          image: ghcr.io/tinymultiverse/jupyterlab-tinyapp:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /home/jovyan
          env:
            - name: TINY_APP_SERVER_URL
              value: http://tinyapp-server.tinyapp.svc.cluster.local:8889
            - name: AI_ENABLED
              value: "false" # TODO make it false
            - name: VOLUME_CLAIM_NAME
              value: my-data
            - name: VOLUME_CLAIM_MOUNT_PATH
              value: "/home/jovyan"
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-data