apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data
  namespace: tinyapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath