// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	tinyappv1alpha1 "github.com/tinymultiverse/tinyapp/pkg/k8s/api/tinyapp/v1alpha1"
	versioned "github.com/tinymultiverse/tinyapp/pkg/k8s/client/tinyapp/clientset/versioned"
	internalinterfaces "github.com/tinymultiverse/tinyapp/pkg/k8s/client/tinyapp/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tinymultiverse/tinyapp/pkg/k8s/client/tinyapp/listers/tinyapp/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TinyAppInformer provides access to a shared informer and lister for
// TinyApps.
type TinyAppInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TinyAppLister
}

type tinyAppInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTinyAppInformer constructs a new informer for TinyApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTinyAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTinyAppInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTinyAppInformer constructs a new informer for TinyApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTinyAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TinymultiverseV1alpha1().TinyApps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TinymultiverseV1alpha1().TinyApps(namespace).Watch(context.TODO(), options)
			},
		},
		&tinyappv1alpha1.TinyApp{},
		resyncPeriod,
		indexers,
	)
}

func (f *tinyAppInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTinyAppInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tinyAppInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tinyappv1alpha1.TinyApp{}, f.defaultInformer)
}

func (f *tinyAppInformer) Lister() v1alpha1.TinyAppLister {
	return v1alpha1.NewTinyAppLister(f.Informer().GetIndexer())
}
