apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-with-tinyapp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: jupyterlab-with-tinyapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
