// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppType int32

const (
	AppType_APP_TYPE_UNKNOWN   AppType = 0
	AppType_APP_TYPE_STREAMLIT AppType = 1
	AppType_APP_TYPE_DASH      AppType = 2
)

// Enum value maps for AppType.
var (
	AppType_name = map[int32]string{
		0: "APP_TYPE_UNKNOWN",
		1: "APP_TYPE_STREAMLIT",
		2: "APP_TYPE_DASH",
	}
	AppType_value = map[string]int32{
		"APP_TYPE_UNKNOWN":   0,
		"APP_TYPE_STREAMLIT": 1,
		"APP_TYPE_DASH":      2,
	}
)

func (x AppType) Enum() *AppType {
	p := new(AppType)
	*p = x
	return p
}

func (x AppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (AppType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x AppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppType.Descriptor instead.
func (AppType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNKNOWN     SourceType = 0
	SourceType_SOURCE_TYPE_GIT         SourceType = 1
	SourceType_SOURCE_TYPE_FILE_SYSTEM SourceType = 2
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNKNOWN",
		1: "SOURCE_TYPE_GIT",
		2: "SOURCE_TYPE_FILE_SYSTEM",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNKNOWN":     0,
		"SOURCE_TYPE_GIT":         1,
		"SOURCE_TYPE_FILE_SYSTEM": 2,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type VolumeClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubPath       string                 `protobuf:"bytes,2,opt,name=subPath,proto3" json:"subPath,omitempty"`
	MountPath     string                 `protobuf:"bytes,3,opt,name=mountPath,proto3" json:"mountPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeClaim) Reset() {
	*x = VolumeClaim{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeClaim) ProtoMessage() {}

func (x *VolumeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeClaim.ProtoReflect.Descriptor instead.
func (*VolumeClaim) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeClaim) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeClaim) GetSubPath() string {
	if x != nil {
		return x.SubPath
	}
	return ""
}

func (x *VolumeClaim) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimName     string                 `protobuf:"bytes,1,opt,name=claimName,proto3" json:"claimName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Volume) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                   // Url to clone
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`               // Git token for authentication. Will be empty in response.
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`                   // Branch or tag name depending on is_tag
	IsTag         bool                   `protobuf:"varint,4,opt,name=is_tag,json=isTag,proto3" json:"is_tag,omitempty"` // If true, ref points to to tag instead of branch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitConfig) Reset() {
	*x = GitConfig{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitConfig) ProtoMessage() {}

func (x *GitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitConfig.ProtoReflect.Descriptor instead.
func (*GitConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GitConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitConfig) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitConfig) GetIsTag() bool {
	if x != nil {
		return x.IsTag
	}
	return false
}

type TinyAppDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Documentation       string                 `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Image               string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	AppType             AppType                `protobuf:"varint,5,opt,name=app_type,json=appType,proto3,enum=tiny.app.proto.AppType" json:"app_type,omitempty"`
	SourceType          SourceType             `protobuf:"varint,6,opt,name=source_type,json=sourceType,proto3,enum=tiny.app.proto.SourceType" json:"source_type,omitempty"`
	GitConfig           *GitConfig             `protobuf:"bytes,7,opt,name=git_config,json=gitConfig,proto3" json:"git_config,omitempty"`
	MainFilePath        string                 `protobuf:"bytes,8,opt,name=main_file_path,json=mainFilePath,proto3" json:"main_file_path,omitempty"`
	Env                 []*EnvVar              `protobuf:"bytes,9,rep,name=env,proto3" json:"env,omitempty"`
	VolumeClaims        []*VolumeClaim         `protobuf:"bytes,10,rep,name=volume_claims,json=volumeClaims,proto3" json:"volume_claims,omitempty"`
	MainVolumeClaimName string                 `protobuf:"bytes,11,opt,name=mainVolumeClaimName,proto3" json:"mainVolumeClaimName,omitempty"`
	AllowedUsers        []string               `protobuf:"bytes,12,rep,name=allowedUsers,proto3" json:"allowedUsers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TinyAppDetail) Reset() {
	*x = TinyAppDetail{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyAppDetail) ProtoMessage() {}

func (x *TinyAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyAppDetail.ProtoReflect.Descriptor instead.
func (*TinyAppDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *TinyAppDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TinyAppDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TinyAppDetail) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *TinyAppDetail) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TinyAppDetail) GetAppType() AppType {
	if x != nil {
		return x.AppType
	}
	return AppType_APP_TYPE_UNKNOWN
}

func (x *TinyAppDetail) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNKNOWN
}

func (x *TinyAppDetail) GetGitConfig() *GitConfig {
	if x != nil {
		return x.GitConfig
	}
	return nil
}

func (x *TinyAppDetail) GetMainFilePath() string {
	if x != nil {
		return x.MainFilePath
	}
	return ""
}

func (x *TinyAppDetail) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TinyAppDetail) GetVolumeClaims() []*VolumeClaim {
	if x != nil {
		return x.VolumeClaims
	}
	return nil
}

func (x *TinyAppDetail) GetMainVolumeClaimName() string {
	if x != nil {
		return x.MainVolumeClaimName
	}
	return ""
}

func (x *TinyAppDetail) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

type TinyAppRelease struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppUrl            string                 `protobuf:"bytes,2,opt,name=app_url,json=appUrl,proto3" json:"app_url,omitempty"`
	CreationTimeStamp string                 `protobuf:"bytes,3,opt,name=creation_time_stamp,json=creationTimeStamp,proto3" json:"creation_time_stamp,omitempty"`
	AppImage          string                 `protobuf:"bytes,4,opt,name=app_image,json=appImage,proto3" json:"app_image,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TinyAppRelease) Reset() {
	*x = TinyAppRelease{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyAppRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyAppRelease) ProtoMessage() {}

func (x *TinyAppRelease) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyAppRelease.ProtoReflect.Descriptor instead.
func (*TinyAppRelease) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *TinyAppRelease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TinyAppRelease) GetAppUrl() string {
	if x != nil {
		return x.AppUrl
	}
	return ""
}

func (x *TinyAppRelease) GetCreationTimeStamp() string {
	if x != nil {
		return x.CreationTimeStamp
	}
	return ""
}

func (x *TinyAppRelease) GetAppImage() string {
	if x != nil {
		return x.AppImage
	}
	return ""
}

type TinyApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRelease    *TinyAppRelease        `protobuf:"bytes,1,opt,name=app_release,json=appRelease,proto3" json:"app_release,omitempty"`
	AppDetail     *TinyAppDetail         `protobuf:"bytes,2,opt,name=app_detail,json=appDetail,proto3" json:"app_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyApp) Reset() {
	*x = TinyApp{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyApp) ProtoMessage() {}

func (x *TinyApp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyApp.ProtoReflect.Descriptor instead.
func (*TinyApp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *TinyApp) GetAppRelease() *TinyAppRelease {
	if x != nil {
		return x.AppRelease
	}
	return nil
}

func (x *TinyApp) GetAppDetail() *TinyAppDetail {
	if x != nil {
		return x.AppDetail
	}
	return nil
}

type CreateTinyAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppDetail     *TinyAppDetail         `protobuf:"bytes,1,opt,name=app_detail,json=appDetail,proto3" json:"app_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTinyAppRequest) Reset() {
	*x = CreateTinyAppRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTinyAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTinyAppRequest) ProtoMessage() {}

func (x *CreateTinyAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTinyAppRequest.ProtoReflect.Descriptor instead.
func (*CreateTinyAppRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTinyAppRequest) GetAppDetail() *TinyAppDetail {
	if x != nil {
		return x.AppDetail
	}
	return nil
}

type CreateTinyAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRelease    *TinyAppRelease        `protobuf:"bytes,1,opt,name=app_release,json=appRelease,proto3" json:"app_release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTinyAppResponse) Reset() {
	*x = CreateTinyAppResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTinyAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTinyAppResponse) ProtoMessage() {}

func (x *CreateTinyAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTinyAppResponse.ProtoReflect.Descriptor instead.
func (*CreateTinyAppResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTinyAppResponse) GetAppRelease() *TinyAppRelease {
	if x != nil {
		return x.AppRelease
	}
	return nil
}

type GetTinyAppAccessMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,2,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTinyAppAccessMetricsRequest) Reset() {
	*x = GetTinyAppAccessMetricsRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppAccessMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppAccessMetricsRequest) ProtoMessage() {}

func (x *GetTinyAppAccessMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppAccessMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetTinyAppAccessMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetTinyAppAccessMetricsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetTinyAppAccessMetricsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

type GetTinyAppAccessMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NumberOfAccess int32                  `protobuf:"varint,1,opt,name=number_of_access,json=numberOfAccess,proto3" json:"number_of_access,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTinyAppAccessMetricsResponse) Reset() {
	*x = GetTinyAppAccessMetricsResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppAccessMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppAccessMetricsResponse) ProtoMessage() {}

func (x *GetTinyAppAccessMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppAccessMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetTinyAppAccessMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetTinyAppAccessMetricsResponse) GetNumberOfAccess() int32 {
	if x != nil {
		return x.NumberOfAccess
	}
	return 0
}

type GetTinyAppUsageMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,2,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTinyAppUsageMetricsRequest) Reset() {
	*x = GetTinyAppUsageMetricsRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppUsageMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppUsageMetricsRequest) ProtoMessage() {}

func (x *GetTinyAppUsageMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppUsageMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetTinyAppUsageMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetTinyAppUsageMetricsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetTinyAppUsageMetricsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

type GetTinyAppUsageMetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuLimit          float64                `protobuf:"fixed64,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit       float64                `protobuf:"fixed64,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	PercentCpuUsed    float64                `protobuf:"fixed64,5,opt,name=percent_cpu_used,json=percentCpuUsed,proto3" json:"percent_cpu_used,omitempty"`
	PercentMemoryUsed float64                `protobuf:"fixed64,6,opt,name=percent_memory_used,json=percentMemoryUsed,proto3" json:"percent_memory_used,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTinyAppUsageMetricsResponse) Reset() {
	*x = GetTinyAppUsageMetricsResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppUsageMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppUsageMetricsResponse) ProtoMessage() {}

func (x *GetTinyAppUsageMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppUsageMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetTinyAppUsageMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetTinyAppUsageMetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetTinyAppUsageMetricsResponse) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *GetTinyAppUsageMetricsResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *GetTinyAppUsageMetricsResponse) GetMemoryLimit() float64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *GetTinyAppUsageMetricsResponse) GetPercentCpuUsed() float64 {
	if x != nil {
		return x.PercentCpuUsed
	}
	return 0
}

func (x *GetTinyAppUsageMetricsResponse) GetPercentMemoryUsed() float64 {
	if x != nil {
		return x.PercentMemoryUsed
	}
	return 0
}

type ListTinyAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppDetail     *TinyAppDetail         `protobuf:"bytes,2,opt,name=app_detail,json=appDetail,proto3" json:"app_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTinyAppsRequest) Reset() {
	*x = ListTinyAppsRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTinyAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTinyAppsRequest) ProtoMessage() {}

func (x *ListTinyAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTinyAppsRequest.ProtoReflect.Descriptor instead.
func (*ListTinyAppsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *ListTinyAppsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListTinyAppsRequest) GetAppDetail() *TinyAppDetail {
	if x != nil {
		return x.AppDetail
	}
	return nil
}

type ListTinyAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*TinyApp             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTinyAppsResponse) Reset() {
	*x = ListTinyAppsResponse{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTinyAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTinyAppsResponse) ProtoMessage() {}

func (x *ListTinyAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTinyAppsResponse.ProtoReflect.Descriptor instead.
func (*ListTinyAppsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListTinyAppsResponse) GetApps() []*TinyApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

type UpdateTinyAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppDetail     *TinyAppDetail         `protobuf:"bytes,2,opt,name=app_detail,json=appDetail,proto3" json:"app_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTinyAppRequest) Reset() {
	*x = UpdateTinyAppRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTinyAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTinyAppRequest) ProtoMessage() {}

func (x *UpdateTinyAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTinyAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateTinyAppRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTinyAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateTinyAppRequest) GetAppDetail() *TinyAppDetail {
	if x != nil {
		return x.AppDetail
	}
	return nil
}

type UpdateTinyAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRelease    *TinyAppRelease        `protobuf:"bytes,1,opt,name=app_release,json=appRelease,proto3" json:"app_release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTinyAppResponse) Reset() {
	*x = UpdateTinyAppResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTinyAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTinyAppResponse) ProtoMessage() {}

func (x *UpdateTinyAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTinyAppResponse.ProtoReflect.Descriptor instead.
func (*UpdateTinyAppResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTinyAppResponse) GetAppRelease() *TinyAppRelease {
	if x != nil {
		return x.AppRelease
	}
	return nil
}

type DeleteTinyAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTinyAppRequest) Reset() {
	*x = DeleteTinyAppRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTinyAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTinyAppRequest) ProtoMessage() {}

func (x *DeleteTinyAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTinyAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteTinyAppRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteTinyAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetTinyAppLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTinyAppLogsRequest) Reset() {
	*x = GetTinyAppLogsRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppLogsRequest) ProtoMessage() {}

func (x *GetTinyAppLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTinyAppLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetTinyAppLogsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetTinyAppLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTinyAppLogsResponse) Reset() {
	*x = GetTinyAppLogsResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTinyAppLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTinyAppLogsResponse) ProtoMessage() {}

func (x *GetTinyAppLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTinyAppLogsResponse.ProtoReflect.Descriptor instead.
func (*GetTinyAppLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetTinyAppLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x0etiny.app.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"Y\n" +
	"\vVolumeClaim\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubPath\x18\x02 \x01(\tR\asubPath\x12\x1c\n" +
	"\tmountPath\x18\x03 \x01(\tR\tmountPath\"&\n" +
	"\x06Volume\x12\x1c\n" +
	"\tclaimName\x18\x01 \x01(\tR\tclaimName\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\\\n" +
	"\tGitConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x15\n" +
	"\x06is_tag\x18\x04 \x01(\bR\x05isTag\"\x94\x04\n" +
	"\rTinyAppDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x122\n" +
	"\bapp_type\x18\x05 \x01(\x0e2\x17.tiny.app.proto.AppTypeR\aappType\x12;\n" +
	"\vsource_type\x18\x06 \x01(\x0e2\x1a.tiny.app.proto.SourceTypeR\n" +
	"sourceType\x128\n" +
	"\n" +
	"git_config\x18\a \x01(\v2\x19.tiny.app.proto.GitConfigR\tgitConfig\x12$\n" +
	"\x0emain_file_path\x18\b \x01(\tR\fmainFilePath\x12(\n" +
	"\x03env\x18\t \x03(\v2\x16.tiny.app.proto.EnvVarR\x03env\x12@\n" +
	"\rvolume_claims\x18\n" +
	" \x03(\v2\x1b.tiny.app.proto.VolumeClaimR\fvolumeClaims\x120\n" +
	"\x13mainVolumeClaimName\x18\v \x01(\tR\x13mainVolumeClaimName\x12\"\n" +
	"\fallowedUsers\x18\f \x03(\tR\fallowedUsers\"\x86\x01\n" +
	"\x0eTinyAppRelease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aapp_url\x18\x02 \x01(\tR\x06appUrl\x12.\n" +
	"\x13creation_time_stamp\x18\x03 \x01(\tR\x11creationTimeStamp\x12\x1b\n" +
	"\tapp_image\x18\x04 \x01(\tR\bappImage\"\x88\x01\n" +
	"\aTinyApp\x12?\n" +
	"\vapp_release\x18\x01 \x01(\v2\x1e.tiny.app.proto.TinyAppReleaseR\n" +
	"appRelease\x12<\n" +
	"\n" +
	"app_detail\x18\x02 \x01(\v2\x1d.tiny.app.proto.TinyAppDetailR\tappDetail\"T\n" +
	"\x14CreateTinyAppRequest\x12<\n" +
	"\n" +
	"app_detail\x18\x01 \x01(\v2\x1d.tiny.app.proto.TinyAppDetailR\tappDetail\"X\n" +
	"\x15CreateTinyAppResponse\x12?\n" +
	"\vapp_release\x18\x01 \x01(\v2\x1e.tiny.app.proto.TinyAppReleaseR\n" +
	"appRelease\"X\n" +
	"\x1eGetTinyAppAccessMetricsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vtime_period\x18\x02 \x01(\tR\n" +
	"timePeriod\"K\n" +
	"\x1fGetTinyAppAccessMetricsResponse\x12(\n" +
	"\x10number_of_access\x18\x01 \x01(\x05R\x0enumberOfAccess\"W\n" +
	"\x1dGetTinyAppUsageMetricsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vtime_period\x18\x02 \x01(\tR\n" +
	"timePeriod\"\xfa\x01\n" +
	"\x1eGetTinyAppUsageMetricsResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\x01R\vmemoryLimit\x12(\n" +
	"\x10percent_cpu_used\x18\x05 \x01(\x01R\x0epercentCpuUsed\x12.\n" +
	"\x13percent_memory_used\x18\x06 \x01(\x01R\x11percentMemoryUsed\"j\n" +
	"\x13ListTinyAppsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12<\n" +
	"\n" +
	"app_detail\x18\x02 \x01(\v2\x1d.tiny.app.proto.TinyAppDetailR\tappDetail\"C\n" +
	"\x14ListTinyAppsResponse\x12+\n" +
	"\x04apps\x18\x01 \x03(\v2\x17.tiny.app.proto.TinyAppR\x04apps\"k\n" +
	"\x14UpdateTinyAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12<\n" +
	"\n" +
	"app_detail\x18\x02 \x01(\v2\x1d.tiny.app.proto.TinyAppDetailR\tappDetail\"X\n" +
	"\x15UpdateTinyAppResponse\x12?\n" +
	"\vapp_release\x18\x01 \x01(\v2\x1e.tiny.app.proto.TinyAppReleaseR\n" +
	"appRelease\"-\n" +
	"\x14DeleteTinyAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\".\n" +
	"\x15GetTinyAppLogsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\",\n" +
	"\x16GetTinyAppLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs*J\n" +
	"\aAppType\x12\x14\n" +
	"\x10APP_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12APP_TYPE_STREAMLIT\x10\x01\x12\x11\n" +
	"\rAPP_TYPE_DASH\x10\x02*W\n" +
	"\n" +
	"SourceType\x12\x17\n" +
	"\x13SOURCE_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSOURCE_TYPE_GIT\x10\x01\x12\x1b\n" +
	"\x17SOURCE_TYPE_FILE_SYSTEM\x10\x022\xed\x06\n" +
	"\rTinyAppServer\x12p\n" +
	"\rCreateTinyApp\x12$.tiny.app.proto.CreateTinyAppRequest\x1a%.tiny.app.proto.CreateTinyAppResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/app\x12k\n" +
	"\fListTinyApps\x12#.tiny.app.proto.ListTinyAppsRequest\x1a$.tiny.app.proto.ListTinyAppsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/apps\x12p\n" +
	"\rUpdateTinyApp\x12$.tiny.app.proto.UpdateTinyAppRequest\x1a%.tiny.app.proto.UpdateTinyAppResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*2\a/v1/app\x12^\n" +
	"\rDeleteTinyApp\x12$.tiny.app.proto.DeleteTinyAppRequest\x1a\x16.google.protobuf.Empty\"\x0f\x82\xd3\xe4\x93\x02\t*\a/v1/app\x12u\n" +
	"\x0eGetTinyAppLogs\x12%.tiny.app.proto.GetTinyAppLogsRequest\x1a&.tiny.app.proto.GetTinyAppLogsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/app-logs\x12\x9a\x01\n" +
	"\x17GetTinyAppAccessMetrics\x12..tiny.app.proto.GetTinyAppAccessMetricsRequest\x1a/.tiny.app.proto.GetTinyAppAccessMetricsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/app-access-metrics\x12\x96\x01\n" +
	"\x16GetTinyAppUsageMetrics\x12-.tiny.app.proto.GetTinyAppUsageMetricsRequest\x1a..tiny.app.proto.GetTinyAppUsageMetricsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/app-usage-metricsB0Z.github.com/tinymultiverse/tinyapp/api/v1/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_goTypes = []any{
	(AppType)(0),                            // 0: tiny.app.proto.AppType
	(SourceType)(0),                         // 1: tiny.app.proto.SourceType
	(*VolumeClaim)(nil),                     // 2: tiny.app.proto.VolumeClaim
	(*Volume)(nil),                          // 3: tiny.app.proto.Volume
	(*EnvVar)(nil),                          // 4: tiny.app.proto.EnvVar
	(*GitConfig)(nil),                       // 5: tiny.app.proto.GitConfig
	(*TinyAppDetail)(nil),                   // 6: tiny.app.proto.TinyAppDetail
	(*TinyAppRelease)(nil),                  // 7: tiny.app.proto.TinyAppRelease
	(*TinyApp)(nil),                         // 8: tiny.app.proto.TinyApp
	(*CreateTinyAppRequest)(nil),            // 9: tiny.app.proto.CreateTinyAppRequest
	(*CreateTinyAppResponse)(nil),           // 10: tiny.app.proto.CreateTinyAppResponse
	(*GetTinyAppAccessMetricsRequest)(nil),  // 11: tiny.app.proto.GetTinyAppAccessMetricsRequest
	(*GetTinyAppAccessMetricsResponse)(nil), // 12: tiny.app.proto.GetTinyAppAccessMetricsResponse
	(*GetTinyAppUsageMetricsRequest)(nil),   // 13: tiny.app.proto.GetTinyAppUsageMetricsRequest
	(*GetTinyAppUsageMetricsResponse)(nil),  // 14: tiny.app.proto.GetTinyAppUsageMetricsResponse
	(*ListTinyAppsRequest)(nil),             // 15: tiny.app.proto.ListTinyAppsRequest
	(*ListTinyAppsResponse)(nil),            // 16: tiny.app.proto.ListTinyAppsResponse
	(*UpdateTinyAppRequest)(nil),            // 17: tiny.app.proto.UpdateTinyAppRequest
	(*UpdateTinyAppResponse)(nil),           // 18: tiny.app.proto.UpdateTinyAppResponse
	(*DeleteTinyAppRequest)(nil),            // 19: tiny.app.proto.DeleteTinyAppRequest
	(*GetTinyAppLogsRequest)(nil),           // 20: tiny.app.proto.GetTinyAppLogsRequest
	(*GetTinyAppLogsResponse)(nil),          // 21: tiny.app.proto.GetTinyAppLogsResponse
	(*emptypb.Empty)(nil),                   // 22: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: tiny.app.proto.TinyAppDetail.app_type:type_name -> tiny.app.proto.AppType
	1,  // 1: tiny.app.proto.TinyAppDetail.source_type:type_name -> tiny.app.proto.SourceType
	5,  // 2: tiny.app.proto.TinyAppDetail.git_config:type_name -> tiny.app.proto.GitConfig
	4,  // 3: tiny.app.proto.TinyAppDetail.env:type_name -> tiny.app.proto.EnvVar
	2,  // 4: tiny.app.proto.TinyAppDetail.volume_claims:type_name -> tiny.app.proto.VolumeClaim
	7,  // 5: tiny.app.proto.TinyApp.app_release:type_name -> tiny.app.proto.TinyAppRelease
	6,  // 6: tiny.app.proto.TinyApp.app_detail:type_name -> tiny.app.proto.TinyAppDetail
	6,  // 7: tiny.app.proto.CreateTinyAppRequest.app_detail:type_name -> tiny.app.proto.TinyAppDetail
	7,  // 8: tiny.app.proto.CreateTinyAppResponse.app_release:type_name -> tiny.app.proto.TinyAppRelease
	6,  // 9: tiny.app.proto.ListTinyAppsRequest.app_detail:type_name -> tiny.app.proto.TinyAppDetail
	8,  // 10: tiny.app.proto.ListTinyAppsResponse.apps:type_name -> tiny.app.proto.TinyApp
	6,  // 11: tiny.app.proto.UpdateTinyAppRequest.app_detail:type_name -> tiny.app.proto.TinyAppDetail
	7,  // 12: tiny.app.proto.UpdateTinyAppResponse.app_release:type_name -> tiny.app.proto.TinyAppRelease
	9,  // 13: tiny.app.proto.TinyAppServer.CreateTinyApp:input_type -> tiny.app.proto.CreateTinyAppRequest
	15, // 14: tiny.app.proto.TinyAppServer.ListTinyApps:input_type -> tiny.app.proto.ListTinyAppsRequest
	17, // 15: tiny.app.proto.TinyAppServer.UpdateTinyApp:input_type -> tiny.app.proto.UpdateTinyAppRequest
	19, // 16: tiny.app.proto.TinyAppServer.DeleteTinyApp:input_type -> tiny.app.proto.DeleteTinyAppRequest
	20, // 17: tiny.app.proto.TinyAppServer.GetTinyAppLogs:input_type -> tiny.app.proto.GetTinyAppLogsRequest
	11, // 18: tiny.app.proto.TinyAppServer.GetTinyAppAccessMetrics:input_type -> tiny.app.proto.GetTinyAppAccessMetricsRequest
	13, // 19: tiny.app.proto.TinyAppServer.GetTinyAppUsageMetrics:input_type -> tiny.app.proto.GetTinyAppUsageMetricsRequest
	10, // 20: tiny.app.proto.TinyAppServer.CreateTinyApp:output_type -> tiny.app.proto.CreateTinyAppResponse
	16, // 21: tiny.app.proto.TinyAppServer.ListTinyApps:output_type -> tiny.app.proto.ListTinyAppsResponse
	18, // 22: tiny.app.proto.TinyAppServer.UpdateTinyApp:output_type -> tiny.app.proto.UpdateTinyAppResponse
	22, // 23: tiny.app.proto.TinyAppServer.DeleteTinyApp:output_type -> google.protobuf.Empty
	21, // 24: tiny.app.proto.TinyAppServer.GetTinyAppLogs:output_type -> tiny.app.proto.GetTinyAppLogsResponse
	12, // 25: tiny.app.proto.TinyAppServer.GetTinyAppAccessMetrics:output_type -> tiny.app.proto.GetTinyAppAccessMetricsResponse
	14, // 26: tiny.app.proto.TinyAppServer.GetTinyAppUsageMetrics:output_type -> tiny.app.proto.GetTinyAppUsageMetricsResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
