apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: { { .Values.server.name } }
    app.kubernetes.io/part-of: tinyapp
  name: { { .Values.server.name } }
  namespace: { { .Values.namespace } }
spec:
  ports:
    - name: grpcport
      port: { { .Values.server.ports.grpc } }
      protocol: TCP
      targetPort: { { .Values.server.ports.grpc } }
    - name: httpport
      port: { { .Values.server.ports.http } }
      protocol: TCP
      targetPort: { { .Values.server.ports.http } }
  selector:
    app.kubernetes.io/name: { { .Values.server.name } }
    app.kubernetes.io/part-of: tinyapp
